[connections.snowflake]

account = "qda62660.east-us-2.azure"
user = "WEINING"
password = "KAnna1934!"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "NASDAQ"
schema = "PUBLIC"
client_session_keep_alive = true